### ISSUE TITLE
Got error when running: nocturne-setup contribute

### ISSUE THREAD

**Issue by 82934162** [privacy-scaling-explorations/p0tion#227]
/opt/homebrew/lib/node_modules/@nocturne-xyz/nocturne-setup/node_modules/solc/soljson.js:133
    process["on"]("unhandledRejection", function (reason) { throw reason; });
                                                            ^

Error: Unable to find the user currently authenticated with Firebase. Verify that the Firebase application is properly configured and repeat user authentication before trying again.
    at getCurrentFirebaseAuthUser (file:///opt/homebrew/lib/node_modules/@nocturne-xyz/nocturne-setup/node_modules/@nocturne-xyz/p0tion-actions/dist/index.mjs:1932:15)
    at checkAuth (file:///opt/homebrew/lib/node_modules/@nocturne-xyz/nocturne-setup/dist/index.js:1552:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.contribute (file:///opt/homebrew/lib/node_modules/@nocturne-xyz/nocturne-setup/dist/index.js:2662:93)
    at async Command.parseAsync (/opt/homebrew/lib/node_modules/@nocturne-xyz/nocturne-setup/node_modules/commander/lib/command.js:935:5)

Node.js v20.5.0

OS: MacOS 13.3.1 (22E261)

**Comment by 82934162** [comment]
Issue resolved.

**Comment by ctrlc03** [comment]
> user authentication before trying again. at getCurrentFirebaseAuthUser (file:///opt/homebrew/lib/node_modules/@nocturne-xyz/nocturne-setup/node_modules/@nocturne-xyz/p0tion-actions/dist/index.mjs:1932:15) at checkAuth (file:///opt/homebrew/lib/node_modules/@nocturne-xyz/nocturne-setup/dist/index.js:1552:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Command.contribute (file:///opt/homebrew/lib/node_modules/@nocturne-xyz/nocturne-setup/dist/index.js:2662:93) at async Command.parseAsync (/opt/homebrew/lib/node_modules/@nocturne-xyz/nocturne-setup/node_modules/commander/lib/command.js:935:5)
> 
> Node.js v20.5.0

that's great to hear!! thanks for using p0tion :)
